package net.smert.lwjgl.examples;

import javax.swing.AbstractListModel;

/**
 *
 * @author Jason Sorensen <sorensenj@smert.net>
 */
public class JFrameMain extends javax.swing.JFrame {

    private final JFrameMainModel jFrameMainModel;
    private final String[] mainArgs;

    /**
     * Creates new form JFrameMain
     *
     * @param args
     */
    public JFrameMain(String[] args) {
        mainArgs = args;

        jFrameMainModel = new JFrameMainModel();

        initComponents();

        AbstractListModel listModel = jFrameMainModel.populateListModel();
        jListMainClasses.setModel(listModel);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneMainClasses = new javax.swing.JScrollPane();
        jListMainClasses = new javax.swing.JList();
        jButtonRunExample = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LWJGL Examples");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("frameMain"); // NOI18N
        setResizable(false);

        jListMainClasses.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPaneMainClasses.setViewportView(jListMainClasses);

        jButtonRunExample.setText("Run Example");
        jButtonRunExample.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunExampleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPaneMainClasses, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addComponent(jButtonRunExample))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneMainClasses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonRunExample)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRunExampleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunExampleActionPerformed
        if (jListMainClasses.getSelectedValue() != null) {
            String selected = jListMainClasses.getSelectedValue().toString();

            jFrameMainModel.runDemo(selected, mainArgs);
        }
    }//GEN-LAST:event_jButtonRunExampleActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRunExample;
    private javax.swing.JList jListMainClasses;
    private javax.swing.JScrollPane jScrollPaneMainClasses;
    // End of variables declaration//GEN-END:variables

}
